### ISSUE TITLE
Integrate Gelato relay

### ISSUE THREAD

**Issue by andyguzmaneth** [semaphore-protocol/semaphore#350]
Similar to how we use Open Zepellin, we want to have Gelato as an option of relayer

**Comment by NathaliaBarreiros** [comment]
Hi @aguzmant103, @vplasencia! I'm interested in this issue and would like to request assignment.

I've noticed work on integrating relayers in PRs [#35](https://github.com/semaphore-protocol/boilerplate/issues/35) and [#44](https://github.com/semaphore-protocol/boilerplate/issues/44).

Could you clarify the remaining tasks for this issue? Is the focus on improving the integration, adding documentation, or something else? Any additional context would be appreciated. Thanks!

**Comment by vplasencia** [comment]
Hey @NathaliaBarreiros!

I think this is already integrated into the boilerplate so maybe this issue should be closed as completed? What do you think @cedoor ?

This other issue is related to this one: https://github.com/semaphore-protocol/semaphore/issues/504

Would you like to take it if this issue is closed?

**Comment by vplasencia** [comment]
Hey @NathaliaBarreiros!

Since this issue was already implemented, I will close it. Please, let me know if you would like to work on https://github.com/semaphore-protocol/semaphore/issues/504 which is similar to the other one you will be working on?
