### ISSUE TITLE
Make the contract tests more atomic and use `loadFixture`

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#706]
### Description

It would be nice to make the tests as atomic as possible and use `loadFixture`.

This can help: https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli-template-contracts-hardhat/test/Feedback.ts

**Comment by 0hwc** [comment]
Hi, I would like to take on this issue! :)

**Comment by vplasencia** [comment]
Hey @waddaboo yes, sure. Do you want me to assign you this issue?

**Comment by 0hwc** [comment]
Yes, please. Thanks!

**Comment by vplasencia** [comment]
@waddaboo done. Please, let us know if you have any questions.

**Comment by 0hwc** [comment]
Hi @vplasencia, I'm currently facing an issue at the `Should not verify a proof if the Merkle tree root is expired` test.

I have created a new group with 0-1s expiry with `createGroup(address,uint256)`, and when I test it with `verifyProof`, it returns `true` instead of the `Semaphore_MerkleTreeRootIsExpired` error.

I have tried using `setTimeOut` to wait out the expiration and `@nomicfoundation/hardhat-toolbox/network-helpers`'s time helpers to advance the block timestamp but still not getting the expected return.

Any ideas on how to work around this?

Edit: Nvm, found the error 😅
