### ISSUE TITLE
Increase timeout for tests generating Semaphore proofs

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#761]
## Description

There is an error when running the test workflow:

```bash
Proof › # generateProof › Should generate a Semaphore proof

    thrown: "Exceeded timeout of 20000 ms for a test.
```

https://github.com/semaphore-protocol/semaphore/actions/runs/8894821856/job/24423871569

**Comment by sripwoud** [comment]
There are 2 different issues in that test(s):
- Timeout for the proof generation:
  Increasing timeout can probably fix it. But I think the root cause is related to https://github.com/privacy-scaling-explorations/zk-kit/issues/280#issuecomment-2092459053
- Structure of the test:
  [Here](https://github.com/semaphore-protocol/semaphore/blob/ddfe4ffd56a2a1be94ef926aa8637dd1f2944907/packages/proof/tests/index.test.ts#L63-L65)
We use a proof defined in the outer scope as parameter. It makes the tests depend on each others. As a result the test suite may produce unexpected results: a successful proof verification test requires the proof generation test having completed first, but jest executes everything in parallel...

**Comment by cedoor** [comment]
@vplasencia we shouldn't need this anymore. Can we close this issue?

**Comment by vplasencia** [comment]
I will close it. The PR was already merged some time ago.
